services:
  playwright-server:
    build: .
    container_name: playwright-server
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
